# Generated by Django 4.2.1 on 2023-05-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0006_alter_post_category_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
